# Generated by Django 4.1.7 on 2023-04-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_user_id_quizz_user_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onGame',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
