# Generated by Django 4.1.7 on 2023-05-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0002_user_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='question',
            field=models.CharField(default='', max_length=255),
        ),
    ]
