# Generated by Django 4.1.7 on 2023-03-31 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OpenQuizz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=255)),
            ],
        ),
    ]
