# Generated by Django 4.1.7 on 2023-04-02 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenQuizz', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
