# Generated by Django 4.1.7 on 2023-03-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=255)),
                ("enonce", models.CharField(max_length=255)),
                ("reponse1", models.CharField(max_length=255)),
                ("reponse2", models.CharField(max_length=255)),
                ("reponse3", models.CharField(max_length=255)),
                ("reponce4", models.CharField(max_length=255)),
                ("reponseVrai", models.CharField(max_length=255)),
                ("reponse", models.CharField(max_length=255)),
                ("explication", models.CharField(default="", max_length=1000)),
                ("qcm", models.BooleanField(default=False)),
            ],
        ),
    ]
