# Generated by Django 4.1.7 on 2023-03-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrateur", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="Questions", new_name="Question",),
    ]
