# Generated by Django 4.1.7 on 2023-03-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrateur", "0002_rename_questions_question"),
    ]

    operations = [
        migrations.RemoveField(model_name="question", name="explication",),
    ]
