# Generated by Django 4.1.7 on 2023-03-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("administrateur", "0003_remove_question_explication"),
    ]

    operations = [
        migrations.RenameField(
            model_name="question", old_name="user", new_name="pseudo",
        ),
    ]
