# Generated by Django 4.1.7 on 2023-03-17 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0005_alter_question_reponce4_alter_question_reponse_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='reponce4',
            new_name='reponse4',
        ),
    ]
