# Generated by Django 4.1.7 on 2023-03-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0006_rename_reponce4_question_reponse4'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
