# Generated by Django 4.1.7 on 2023-03-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0008_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=255)),
                ('questions', models.JSONField()),
                ('mode', models.CharField(max_length=255)),
                ('timer', models.IntegerField(default=0)),
                ('afficher', models.BooleanField(default=False)),
                ('stocker', models.BooleanField(default=False)),
            ],
        ),
    ]
