# Generated by Django 4.1.7 on 2023-03-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0010_remove_quizz_questions_quizz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
