# Generated by Django 4.1.7 on 2023-03-31 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0016_alter_quizz_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
