# Generated by Django 4.1.7 on 2023-04-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0019_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
