# Generated by Django 4.1.7 on 2023-04-03 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0020_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='intitule',
            field=models.CharField(default='', max_length=255),
        ),
    ]
