# Generated by Django 4.1.7 on 2023-04-06 11:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0023_quizz_ongame'),
    ]

    operations = [
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idQuizz', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('idQuestion', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
    ]
