# Generated by Django 4.1.7 on 2023-04-06 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0024_association'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizz',
            name='questions',
        ),
    ]
