# Generated by Django 4.1.7 on 2023-04-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0025_remove_quizz_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(max_length=255)),
                ('theme', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
