# Generated by Django 4.1.7 on 2023-04-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0026_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='numero',
            field=models.IntegerField(default=0),
        ),
    ]
