# Generated by Django 4.1.7 on 2023-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0027_theme_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='association',
            name='idQuestion',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='association',
            name='idQuizz',
            field=models.UUIDField(),
        ),
    ]
