# Generated by Django 4.1.7 on 2023-05-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrateur', '0029_alter_quizz_ongame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizz',
            name='onGame',
            field=models.CharField(default='0000000', max_length=10),
        ),
    ]
